execute @s[scores={stktrigtmr=10}] ~ ~ ~ title @a title §210
execute @s[scores={stktrigtmr=9}] ~ ~ ~ title @a title §29
execute @s[scores={stktrigtmr=8}] ~ ~ ~ title @a title §28
execute @s[scores={stktrigtmr=7}] ~ ~ ~ title @a title §e7
execute @s[scores={stktrigtmr=6}] ~ ~ ~ title @a title §e6
execute @s[scores={stktrigtmr=5}] ~ ~ ~ title @a title §e5
execute @s[scores={stktrigtmr=4}] ~ ~ ~ title @a title §e4
execute @s[scores={stktrigtmr=3}] ~ ~ ~ title @a title §43
execute @s[scores={stktrigtmr=2}] ~ ~ ~ title @a title §42
execute @s[scores={stktrigtmr=1}] ~ ~ ~ title @a title §41
execute @s[scores={stktrigtmr=0}] ~ ~ ~ title @a title §40