execute @e[type=cyd:collectible_storage,tag=sub1] ~ ~ ~ event entity @e[type=cyd:c_item_asub_1] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sub1] ~ ~ ~ tag @s remove sub1
execute @e[type=cyd:collectible_storage,tag=sub2] ~ ~ ~ event entity @e[type=cyd:c_item_asub_2] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sub2] ~ ~ ~ tag @s remove sub2
execute @e[type=cyd:collectible_storage,tag=sub3] ~ ~ ~ event entity @e[type=cyd:c_item_asub_3] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sub3] ~ ~ ~ tag @s remove sub3
execute @e[type=cyd:collectible_storage,tag=bratt1] ~ ~ ~ event entity @e[type=cyd:c_item_bl_1] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=bratt1] ~ ~ ~ tag @s remove bratt1
execute @e[type=cyd:collectible_storage,tag=bratt2] ~ ~ ~ event entity @e[type=cyd:c_item_bl_2] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=bratt2] ~ ~ ~ tag @s remove bratt2
execute @e[type=cyd:collectible_storage,tag=bratt3] ~ ~ ~ event entity @e[type=cyd:c_item_bl_3] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=bratt3] ~ ~ ~ tag @s remove bratt3
execute @e[type=cyd:collectible_storage,tag=china1] ~ ~ ~ event entity @e[type=cyd:c_item_ct_1] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=china1] ~ ~ ~ tag @s remove china1
execute @e[type=cyd:collectible_storage,tag=china2] ~ ~ ~ event entity @e[type=cyd:c_item_ct_2] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=china2] ~ ~ ~ tag @s remove china2
execute @e[type=cyd:collectible_storage,tag=china3] ~ ~ ~ event entity @e[type=cyd:c_item_ct_3] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=china3] ~ ~ ~ tag @s remove china3
execute @e[type=cyd:collectible_storage,tag=china4] ~ ~ ~ event entity @e[type=cyd:c_item_ct_4] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=china4] ~ ~ ~ tag @s remove china4
execute @e[type=cyd:collectible_storage,tag=china5] ~ ~ ~ event entity @e[type=cyd:c_item_ct_5] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=china5] ~ ~ ~ tag @s remove china5
execute @e[type=cyd:collectible_storage,tag=china6] ~ ~ ~ event entity @e[type=cyd:c_item_ct_6] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=china6] ~ ~ ~ tag @s remove china6
execute @e[type=cyd:collectible_storage,tag=macho1] ~ ~ ~ event entity @e[type=cyd:c_item_emm_1] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=macho1] ~ ~ ~ tag @s remove macho1
execute @e[type=cyd:collectible_storage,tag=macho2] ~ ~ ~ event entity @e[type=cyd:c_item_emm_2] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=macho2] ~ ~ ~ tag @s remove macho2
execute @e[type=cyd:collectible_storage,tag=macho3] ~ ~ ~ event entity @e[type=cyd:c_item_emm_3] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=macho3] ~ ~ ~ tag @s remove macho3
execute @e[type=cyd:collectible_storage,tag=macho4] ~ ~ ~ event entity @e[type=cyd:c_item_emm_4] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=macho4] ~ ~ ~ tag @s remove macho4
execute @e[type=cyd:collectible_storage,tag=macho5] ~ ~ ~ event entity @e[type=cyd:c_item_emm_5] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=macho5] ~ ~ ~ tag @s remove macho5
execute @e[type=cyd:collectible_storage,tag=free1] ~ ~ ~ event entity @e[type=cyd:c_item_free_1] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=free1] ~ ~ ~ tag @s remove free1
execute @e[type=cyd:collectible_storage,tag=free2] ~ ~ ~ event entity @e[type=cyd:c_item_free_2] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=free2] ~ ~ ~ tag @s remove free2
execute @e[type=cyd:collectible_storage,tag=free3] ~ ~ ~ event entity @e[type=cyd:c_item_free_3] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=free3] ~ ~ ~ tag @s remove free3
execute @e[type=cyd:collectible_storage,tag=free4] ~ ~ ~ event entity @e[type=cyd:c_item_free_4] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=free4] ~ ~ ~ tag @s remove free4
execute @e[type=cyd:collectible_storage,tag=free5] ~ ~ ~ event entity @e[type=cyd:c_item_free_5] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=free5] ~ ~ ~ tag @s remove free5
execute @e[type=cyd:collectible_storage,tag=home1] ~ ~ ~ event entity @e[type=cyd:c_item_ht_1] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=home1] ~ ~ ~ tag @s remove home1
execute @e[type=cyd:collectible_storage,tag=home2] ~ ~ ~ event entity @e[type=cyd:c_item_ht_2] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=home2] ~ ~ ~ tag @s remove home2
execute @e[type=cyd:collectible_storage,tag=home3] ~ ~ ~ event entity @e[type=cyd:c_item_ht_3] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=home3] ~ ~ ~ tag @s remove home3
execute @e[type=cyd:collectible_storage,tag=home4] ~ ~ ~ event entity @e[type=cyd:c_item_ht_4] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=home4] ~ ~ ~ tag @s remove home4
execute @e[type=cyd:collectible_storage,tag=home5] ~ ~ ~ event entity @e[type=cyd:c_item_ht_5] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=home5] ~ ~ ~ tag @s remove home5
execute @e[type=cyd:collectible_storage,tag=home6] ~ ~ ~ event entity @e[type=cyd:c_item_ht_6] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=home6] ~ ~ ~ tag @s remove home6
execute @e[type=cyd:collectible_storage,tag=home7] ~ ~ ~ event entity @e[type=cyd:c_item_ht_7] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=home7] ~ ~ ~ tag @s remove home7
execute @e[type=cyd:collectible_storage,tag=resident1] ~ ~ ~ event entity @e[type=cyd:c_item_ra_1] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=resident1] ~ ~ ~ tag @s remove resident1
execute @e[type=cyd:collectible_storage,tag=resident2] ~ ~ ~ event entity @e[type=cyd:c_item_ra_2] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=resident2] ~ ~ ~ tag @s remove resident2
execute @e[type=cyd:collectible_storage,tag=resident3] ~ ~ ~ event entity @e[type=cyd:c_item_ra_3] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=resident3] ~ ~ ~ tag @s remove resident3
execute @e[type=cyd:collectible_storage,tag=resident4] ~ ~ ~ event entity @e[type=cyd:c_item_ra_4] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=resident4] ~ ~ ~ tag @s remove resident4
execute @e[type=cyd:collectible_storage,tag=resident5] ~ ~ ~ event entity @e[type=cyd:c_item_ra_5] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=resident5] ~ ~ ~ tag @s remove resident5
execute @e[type=cyd:collectible_storage,tag=resident6] ~ ~ ~ event entity @e[type=cyd:c_item_ra_6] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=resident6] ~ ~ ~ tag @s remove resident6
execute @e[type=cyd:collectible_storage,tag=resident7] ~ ~ ~ event entity @e[type=cyd:c_item_ra_7] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=resident7] ~ ~ ~ tag @s remove resident7
execute @e[type=cyd:collectible_storage,tag=resident8] ~ ~ ~ event entity @e[type=cyd:c_item_ra_8] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=resident8] ~ ~ ~ tag @s remove resident8
execute @e[type=cyd:collectible_storage,tag=resident9] ~ ~ ~ event entity @e[type=cyd:c_item_ra_9] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=resident9] ~ ~ ~ tag @s remove resident9
execute @e[type=cyd:collectible_storage,tag=sanfran1] ~ ~ ~ event entity @e[type=cyd:c_item_sf_1] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran1] ~ ~ ~ tag @s remove sanfran1
execute @e[type=cyd:collectible_storage,tag=sanfran2] ~ ~ ~ event entity @e[type=cyd:c_item_sf_2] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran2] ~ ~ ~ tag @s remove sanfran2
execute @e[type=cyd:collectible_storage,tag=sanfran3] ~ ~ ~ event entity @e[type=cyd:c_item_sf_3] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran3] ~ ~ ~ tag @s remove sanfran3
execute @e[type=cyd:collectible_storage,tag=sanfran4] ~ ~ ~ event entity @e[type=cyd:c_item_sf_4] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran4] ~ ~ ~ tag @s remove sanfran4
execute @e[type=cyd:collectible_storage,tag=sanfran5] ~ ~ ~ event entity @e[type=cyd:c_item_sf_5] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran5] ~ ~ ~ tag @s remove sanfran5
execute @e[type=cyd:collectible_storage,tag=sanfran6] ~ ~ ~ event entity @e[type=cyd:c_item_sf_6] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran6] ~ ~ ~ tag @s remove sanfran6
execute @e[type=cyd:collectible_storage,tag=sanfran7] ~ ~ ~ event entity @e[type=cyd:c_item_sf_7] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran7] ~ ~ ~ tag @s remove sanfran7
execute @e[type=cyd:collectible_storage,tag=sanfran8] ~ ~ ~ event entity @e[type=cyd:c_item_sf_8] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran8] ~ ~ ~ tag @s remove sanfran8
execute @e[type=cyd:collectible_storage,tag=sanfran9] ~ ~ ~ event entity @e[type=cyd:c_item_sf_9] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran9] ~ ~ ~ tag @s remove sanfran9
execute @e[type=cyd:collectible_storage,tag=sanfran10] ~ ~ ~ event entity @e[type=cyd:c_item_sf_10] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran10] ~ ~ ~ tag @s remove sanfran10
execute @e[type=cyd:collectible_storage,tag=sanfran11] ~ ~ ~ event entity @e[type=cyd:c_item_sf_11] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran11] ~ ~ ~ tag @s remove sanfran11
execute @e[type=cyd:collectible_storage,tag=sanfran12] ~ ~ ~ event entity @e[type=cyd:c_item_sf_12] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=sanfran12] ~ ~ ~ tag @s remove sanfran12
execute @e[type=cyd:collectible_storage,tag=vector1] ~ ~ ~ event entity @e[type=cyd:c_item_vf_1] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=vector1] ~ ~ ~ tag @s remove vector1
execute @e[type=cyd:collectible_storage,tag=vector2] ~ ~ ~ event entity @e[type=cyd:c_item_vf_2] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=vector2] ~ ~ ~ tag @s remove vector2
execute @e[type=cyd:collectible_storage,tag=vector3] ~ ~ ~ event entity @e[type=cyd:c_item_vf_3] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=vector3] ~ ~ ~ tag @s remove vector3
execute @e[type=cyd:collectible_storage,tag=vector4] ~ ~ ~ event entity @e[type=cyd:c_item_vf_4] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=vector4] ~ ~ ~ tag @s remove vector4
execute @e[type=cyd:collectible_storage,tag=vector5] ~ ~ ~ event entity @e[type=cyd:c_item_vf_5] evt:sid_1
execute @e[type=cyd:collectible_storage,tag=vector5] ~ ~ ~ tag @s remove vector5