execute @s[type=cyd:c_item_asub_1] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sub1] ~ ~ ~ event entity @e[type=cyd:c_item_asub_1] evt:sid_1
execute @s[type=cyd:c_item_asub_2] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sub2] ~ ~ ~ event entity @e[type=cyd:c_item_asub_2] evt:sid_1
execute @s[type=cyd:c_item_asub_3] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sub3] ~ ~ ~ event entity @e[type=cyd:c_item_asub_3] evt:sid_1
execute @s[type=cyd:c_item_bl_1] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=bratt1] ~ ~ ~ event entity @e[type=cyd:c_item_bl_1] evt:sid_1
execute @s[type=cyd:c_item_bl_2] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=bratt2] ~ ~ ~ event entity @e[type=cyd:c_item_bl_2] evt:sid_1
execute @s[type=cyd:c_item_bl_3] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=bratt3] ~ ~ ~ event entity @e[type=cyd:c_item_bl_3] evt:sid_1
execute @s[type=cyd:c_item_ct_1] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=china1] ~ ~ ~ event entity @e[type=cyd:c_item_ct_1] evt:sid_1
execute @s[type=cyd:c_item_ct_2] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=china2] ~ ~ ~ event entity @e[type=cyd:c_item_ct_2] evt:sid_1
execute @s[type=cyd:c_item_ct_3] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=china3] ~ ~ ~ event entity @e[type=cyd:c_item_ct_3] evt:sid_1
execute @s[type=cyd:c_item_ct_4] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=china4] ~ ~ ~ event entity @e[type=cyd:c_item_ct_4] evt:sid_1
execute @s[type=cyd:c_item_ct_5] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=china5] ~ ~ ~ event entity @e[type=cyd:c_item_ct_5] evt:sid_1
execute @s[type=cyd:c_item_ct_6] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=china6] ~ ~ ~ event entity @e[type=cyd:c_item_ct_6] evt:sid_1
execute @s[type=cyd:c_item_emm_1] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=macho1] ~ ~ ~ event entity @e[type=cyd:c_item_emm_1] evt:sid_1
execute @s[type=cyd:c_item_emm_2] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=macho2] ~ ~ ~ event entity @e[type=cyd:c_item_emm_2] evt:sid_1
execute @s[type=cyd:c_item_emm_3] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=macho3] ~ ~ ~ event entity @e[type=cyd:c_item_emm_3] evt:sid_1
execute @s[type=cyd:c_item_emm_4] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=macho4] ~ ~ ~ event entity @e[type=cyd:c_item_emm_4] evt:sid_1
execute @s[type=cyd:c_item_emm_5] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=macho5] ~ ~ ~ event entity @e[type=cyd:c_item_emm_5] evt:sid_1
execute @s[type=cyd:c_item_free_1] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=free1] ~ ~ ~ event entity @e[type=cyd:c_item_free_1] evt:sid_1
execute @s[type=cyd:c_item_free_2] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=free2] ~ ~ ~ event entity @e[type=cyd:c_item_free_2] evt:sid_1
execute @s[type=cyd:c_item_free_3] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=free3] ~ ~ ~ event entity @e[type=cyd:c_item_free_3] evt:sid_1
execute @s[type=cyd:c_item_free_4] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=free4] ~ ~ ~ event entity @e[type=cyd:c_item_free_4] evt:sid_1
execute @s[type=cyd:c_item_free_5] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=free5] ~ ~ ~ event entity @e[type=cyd:c_item_free_5] evt:sid_1
execute @s[type=cyd:c_item_ht_1] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=home1] ~ ~ ~ event entity @e[type=cyd:c_item_ht_1] evt:sid_1
execute @s[type=cyd:c_item_ht_2] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=home2] ~ ~ ~ event entity @e[type=cyd:c_item_ht_2] evt:sid_1
execute @s[type=cyd:c_item_ht_3] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=home3] ~ ~ ~ event entity @e[type=cyd:c_item_ht_3] evt:sid_1
execute @s[type=cyd:c_item_ht_4] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=home4] ~ ~ ~ event entity @e[type=cyd:c_item_ht_4] evt:sid_1
execute @s[type=cyd:c_item_ht_5] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=home5] ~ ~ ~ event entity @e[type=cyd:c_item_ht_5] evt:sid_1
execute @s[type=cyd:c_item_ht_6] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=home6] ~ ~ ~ event entity @e[type=cyd:c_item_ht_6] evt:sid_1
execute @s[type=cyd:c_item_ht_7] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=home7] ~ ~ ~ event entity @e[type=cyd:c_item_ht_7] evt:sid_1
execute @s[type=cyd:c_item_ra_1] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=resident1] ~ ~ ~ event entity @e[type=cyd:c_item_ra_1] evt:sid_1
execute @s[type=cyd:c_item_ra_2] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=resident2] ~ ~ ~ event entity @e[type=cyd:c_item_ra_2] evt:sid_1
execute @s[type=cyd:c_item_ra_3] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=resident3] ~ ~ ~ event entity @e[type=cyd:c_item_ra_3] evt:sid_1
execute @s[type=cyd:c_item_ra_4] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=resident4] ~ ~ ~ event entity @e[type=cyd:c_item_ra_4] evt:sid_1
execute @s[type=cyd:c_item_ra_5] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=resident5] ~ ~ ~ event entity @e[type=cyd:c_item_ra_5] evt:sid_1
execute @s[type=cyd:c_item_ra_6] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=resident6] ~ ~ ~ event entity @e[type=cyd:c_item_ra_6] evt:sid_1
execute @s[type=cyd:c_item_ra_7] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=resident7] ~ ~ ~ event entity @e[type=cyd:c_item_ra_7] evt:sid_1
execute @s[type=cyd:c_item_ra_8] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=resident8] ~ ~ ~ event entity @e[type=cyd:c_item_ra_8] evt:sid_1
execute @s[type=cyd:c_item_ra_9] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=resident9] ~ ~ ~ event entity @e[type=cyd:c_item_ra_9] evt:sid_1
execute @s[type=cyd:c_item_sf_1] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran1] ~ ~ ~ event entity @e[type=cyd:c_item_sf_1] evt:sid_1
execute @s[type=cyd:c_item_sf_2] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran2] ~ ~ ~ event entity @e[type=cyd:c_item_sf_2] evt:sid_1
execute @s[type=cyd:c_item_sf_3] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran3] ~ ~ ~ event entity @e[type=cyd:c_item_sf_3] evt:sid_1
execute @s[type=cyd:c_item_sf_4] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran4] ~ ~ ~ event entity @e[type=cyd:c_item_sf_4] evt:sid_1
execute @s[type=cyd:c_item_sf_5] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran5] ~ ~ ~ event entity @e[type=cyd:c_item_sf_5] evt:sid_1
execute @s[type=cyd:c_item_sf_6] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran6] ~ ~ ~ event entity @e[type=cyd:c_item_sf_6] evt:sid_1
execute @s[type=cyd:c_item_sf_7] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran7] ~ ~ ~ event entity @e[type=cyd:c_item_sf_7] evt:sid_1
execute @s[type=cyd:c_item_sf_8] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran8] ~ ~ ~ event entity @e[type=cyd:c_item_sf_8] evt:sid_1
execute @s[type=cyd:c_item_sf_9] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran9] ~ ~ ~ event entity @e[type=cyd:c_item_sf_9] evt:sid_1
execute @s[type=cyd:c_item_sf_10] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran10] ~ ~ ~ event entity @e[type=cyd:c_item_sf_10] evt:sid_1
execute @s[type=cyd:c_item_sf_11] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran11] ~ ~ ~ event entity @e[type=cyd:c_item_sf_11] evt:sid_1
execute @s[type=cyd:c_item_sf_12] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=sanfran12] ~ ~ ~ event entity @e[type=cyd:c_item_sf_12] evt:sid_1
execute @s[type=cyd:c_item_vf_1] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=vector1] ~ ~ ~ event entity @e[type=cyd:c_item_vf_1] evt:sid_1
execute @s[type=cyd:c_item_vf_2] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=vector2] ~ ~ ~ event entity @e[type=cyd:c_item_vf_2] evt:sid_1
execute @s[type=cyd:c_item_vf_3] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=vector3] ~ ~ ~ event entity @e[type=cyd:c_item_vf_3] evt:sid_1
execute @s[type=cyd:c_item_vf_4] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=vector4] ~ ~ ~ event entity @e[type=cyd:c_item_vf_4] evt:sid_1
execute @s[type=cyd:c_item_vf_5] ~ ~ ~ execute @e[type=cyd:collectible_storage,tag=vector5] ~ ~ ~ event entity @e[type=cyd:c_item_vf_5] evt:sid_1