execute @e[type=cyd:collectible_storage,tag=bellebike] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=1}] ~ ~ ~ function playerbase/vehicle_bellebike
execute @e[type=cyd:collectible_storage,tag=bellebike] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=1}] ~ ~ ~ function playerbase/vehicle_cutscene
execute @e[type=cyd:collectible_storage,tag=bellecar] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=2}] ~ ~ ~ function playerbase/vehicle_bellecar
execute @e[type=cyd:collectible_storage,tag=bellecar] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=2}] ~ ~ ~ function playerbase/vehicle_cutscene
execute @e[type=cyd:collectible_storage,tag=grubike] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=3}] ~ ~ ~ function playerbase/vehicle_grubike
execute @e[type=cyd:collectible_storage,tag=grubike] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=3}] ~ ~ ~ function playerbase/vehicle_cutscene
execute @e[type=cyd:collectible_storage,tag=grucar] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=4}] ~ ~ ~ function playerbase/vehicle_grucar
execute @e[type=cyd:collectible_storage,tag=grucar] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=4}] ~ ~ ~ function playerbase/vehicle_cutscene
execute @e[type=cyd:collectible_storage,tag=dru] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=5}] ~ ~ ~ function playerbase/vehicle_drucar
execute @e[type=cyd:collectible_storage,tag=dru] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=5}] ~ ~ ~ function playerbase/vehicle_cutscene
execute @e[type=cyd:collectible_storage,tag=jeanclawed] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=6}] ~ ~ ~ function playerbase/vehicle_jeanclawed
execute @e[type=cyd:collectible_storage,tag=jeanclawed] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=6}] ~ ~ ~ function playerbase/vehicle_cutscene
execute @e[type=cyd:collectible_storage,tag=stronghold] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=7}] ~ ~ ~ function playerbase/vehicle_stronghold
execute @e[type=cyd:collectible_storage,tag=stronghold] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=7}] ~ ~ ~ function playerbase/vehicle_cutscene
execute @e[type=cyd:collectible_storage,tag=nunchuck] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=8}] ~ ~ ~ function playerbase/vehicle_nunchuck
execute @e[type=cyd:collectible_storage,tag=nunchuck] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=8}] ~ ~ ~ function playerbase/vehicle_cutscene
execute @e[type=cyd:collectible_storage,tag=sven] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=9}] ~ ~ ~ function playerbase/vehicle_sven
execute @e[type=cyd:collectible_storage,tag=sven] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=9}] ~ ~ ~ function playerbase/vehicle_cutscene
execute @e[type=cyd:collectible_storage,tag=flying] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=10}] ~ ~ ~ function playerbase/vehicle_flying
execute @e[type=cyd:collectible_storage,tag=flying] ~ ~ ~ execute @e[type=cyd:vehicle_container,scores={collectible=10}] ~ ~ ~ function playerbase/vehicle_cutscene