#remove ticking areas

tickingarea remove chs
tickingarea remove fix
tickingarea remove fix2
tickingarea remove fix3
tickingarea remove fix4
tickingarea remove fix5
tickingarea remove fix6
tickingarea remove fix7
tickingarea remove fix8
tickingarea remove fix9
tickingarea remove fix10
tickingarea remove fix11
tickingarea remove fix12
tickingarea remove fix13
tickingarea remove fix14
tickingarea remove fix15
tickingarea remove fix16
tickingarea remove fix17
tickingarea remove fix18
tickingarea remove fix19
tickingarea remove fix20
tickingarea remove fix21
tickingarea remove fix22
tickingarea remove fix23
tickingarea remove fix24
tickingarea remove fix25
tickingarea remove fix26
tickingarea remove fix27