#used for laser diagonal
execute @s ^-10 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-10 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^-9 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-9 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^-8 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-8 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^-7 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-7 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^-6 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-6 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^-5 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-5 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^-4 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-4 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^-3 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-3 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^-2 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-2 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^-1 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^-1 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^ ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^ ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^1 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^1 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^2 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^2 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^3 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^3 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^4 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^4 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^5 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^5 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^6 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^6 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^7 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^7 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^8 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^8 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^9 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^9 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
execute @s ^10 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add caught_wk
execute @s ^10 ^ ^ execute @p[r=0.5,tag=!dev] ~ ~ ~ tag @s add laser_sound
