execute @s[tag=player1] ~ ~ ~ execute @e[type=cyd:sticky_return,c=1] ~ ~ ~ tp @s ^ ^ ^1 facing @p[tag=player1]
execute @s[tag=player2] ~ ~ ~ execute @e[type=cyd:sticky_return,c=1] ~ ~ ~ tp @s ^ ^ ^1 facing @p[tag=player2]
execute @s[tag=player3] ~ ~ ~ execute @e[type=cyd:sticky_return,c=1] ~ ~ ~ tp @s ^ ^ ^1 facing @p[tag=player3]
execute @s[tag=player4] ~ ~ ~ execute @e[type=cyd:sticky_return,c=1] ~ ~ ~ tp @s ^ ^ ^1 facing @p[tag=player4]
execute @s[tag=player5] ~ ~ ~ execute @e[type=cyd:sticky_return,c=1] ~ ~ ~ tp @s ^ ^ ^1 facing @p[tag=player5]
execute @s[tag=player6] ~ ~ ~ execute @e[type=cyd:sticky_return,c=1] ~ ~ ~ tp @s ^ ^ ^1 facing @p[tag=player6]
execute @s[tag=player7] ~ ~ ~ execute @e[type=cyd:sticky_return,c=1] ~ ~ ~ tp @s ^ ^ ^1 facing @p[tag=player7]
execute @s[tag=player8] ~ ~ ~ execute @e[type=cyd:sticky_return,c=1] ~ ~ ~ tp @s ^ ^ ^1 facing @p[tag=player8]